### ISSUE TITLE
在OpenWrt上一直显示fake request

### ISSUE THREAD

**Issue by ekenchan** [pagxir/toy2vpn#4]
我在OpenWrt上用tun2socks创建了一个tun，指向本地ss的监听端口，然后添加某些外国ip路由规则通过tun，尝试telnet时一直显示fake request，不通

**Comment by pagxir** [comment]
参见：http://www.oigle.cc/archives/583 配置防火墙允许端口访问。

**Comment by ekenchan** [comment]
谢谢，可以用了，赞。
希望项目不要停，可以继续开发
